export const users = [
  {
    login: 'mojombo',
    id: 1,
    node_id: 'MDQ6VXNlcjE=',
    avatar_url: 'https://avatars.githubusercontent.com/u/1?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mojombo',
    html_url: 'https://github.com/mojombo',
    followers_url: 'https://api.github.com/users/mojombo/followers',
    following_url:
      'https://api.github.com/users/mojombo/following{/other_user}',
    gists_url: 'https://api.github.com/users/mojombo/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mojombo/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mojombo/subscriptions',
    organizations_url: 'https://api.github.com/users/mojombo/orgs',
    repos_url: 'https://api.github.com/users/mojombo/repos',
    events_url: 'https://api.github.com/users/mojombo/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mojombo/received_events',
    type: 'User',
    site_admin: false,
    name: 'Tom Preston-Werner',
    company: '@chatterbugapp, @redwoodjs, @preston-werner-ventures ',
    blog: 'http://tom.preston-werner.com',
    location: 'San Francisco',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: 'mojombo',
    public_repos: 63,
    public_gists: 62,
    followers: 22885,
    following: 11,
    created_at: '2007-10-20T05:24:19Z',
    updated_at: '2022-03-14T20:26:53Z',
  },
  {
    login: 'defunkt',
    id: 2,
    node_id: 'MDQ6VXNlcjI=',
    avatar_url: 'https://avatars.githubusercontent.com/u/2?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/defunkt',
    html_url: 'https://github.com/defunkt',
    followers_url: 'https://api.github.com/users/defunkt/followers',
    following_url:
      'https://api.github.com/users/defunkt/following{/other_user}',
    gists_url: 'https://api.github.com/users/defunkt/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/defunkt/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/defunkt/subscriptions',
    organizations_url: 'https://api.github.com/users/defunkt/orgs',
    repos_url: 'https://api.github.com/users/defunkt/repos',
    events_url: 'https://api.github.com/users/defunkt/events{/privacy}',
    received_events_url: 'https://api.github.com/users/defunkt/received_events',
    type: 'User',
    site_admin: false,
    name: 'Chris Wanstrath',
    company: null,
    blog: 'http://chriswanstrath.com/',
    location: null,
    email: null,
    hireable: null,
    bio: '🍔',
    twitter_username: null,
    public_repos: 107,
    public_gists: 273,
    followers: 21403,
    following: 210,
    created_at: '2007-10-20T05:24:19Z',
    updated_at: '2022-02-09T18:00:53Z',
  },
  {
    login: 'pjhyett',
    id: 3,
    node_id: 'MDQ6VXNlcjM=',
    avatar_url: 'https://avatars.githubusercontent.com/u/3?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/pjhyett',
    html_url: 'https://github.com/pjhyett',
    followers_url: 'https://api.github.com/users/pjhyett/followers',
    following_url:
      'https://api.github.com/users/pjhyett/following{/other_user}',
    gists_url: 'https://api.github.com/users/pjhyett/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/pjhyett/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/pjhyett/subscriptions',
    organizations_url: 'https://api.github.com/users/pjhyett/orgs',
    repos_url: 'https://api.github.com/users/pjhyett/repos',
    events_url: 'https://api.github.com/users/pjhyett/events{/privacy}',
    received_events_url: 'https://api.github.com/users/pjhyett/received_events',
    type: 'User',
    site_admin: false,
    name: 'PJ Hyett',
    company: 'GitHub, Inc.',
    blog: 'https://hyett.com',
    location: 'San Francisco',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 8,
    public_gists: 21,
    followers: 8224,
    following: 30,
    created_at: '2008-01-07T17:54:22Z',
    updated_at: '2022-02-05T16:34:17Z',
  },
  {
    login: 'wycats',
    id: 4,
    node_id: 'MDQ6VXNlcjQ=',
    avatar_url: 'https://avatars.githubusercontent.com/u/4?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/wycats',
    html_url: 'https://github.com/wycats',
    followers_url: 'https://api.github.com/users/wycats/followers',
    following_url: 'https://api.github.com/users/wycats/following{/other_user}',
    gists_url: 'https://api.github.com/users/wycats/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/wycats/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/wycats/subscriptions',
    organizations_url: 'https://api.github.com/users/wycats/orgs',
    repos_url: 'https://api.github.com/users/wycats/repos',
    events_url: 'https://api.github.com/users/wycats/events{/privacy}',
    received_events_url: 'https://api.github.com/users/wycats/received_events',
    type: 'User',
    site_admin: false,
    name: 'Yehuda Katz',
    company: '@tildeio ',
    blog: 'http://yehudakatz.com',
    location: 'Portland, OR',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: 'wycats',
    public_repos: 250,
    public_gists: 753,
    followers: 9911,
    following: 5,
    created_at: '2008-01-12T05:38:33Z',
    updated_at: '2022-03-04T01:24:23Z',
  },
  {
    login: 'ezmobius',
    id: 5,
    node_id: 'MDQ6VXNlcjU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/5?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/ezmobius',
    html_url: 'https://github.com/ezmobius',
    followers_url: 'https://api.github.com/users/ezmobius/followers',
    following_url:
      'https://api.github.com/users/ezmobius/following{/other_user}',
    gists_url: 'https://api.github.com/users/ezmobius/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/ezmobius/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/ezmobius/subscriptions',
    organizations_url: 'https://api.github.com/users/ezmobius/orgs',
    repos_url: 'https://api.github.com/users/ezmobius/repos',
    events_url: 'https://api.github.com/users/ezmobius/events{/privacy}',
    received_events_url:
      'https://api.github.com/users/ezmobius/received_events',
    type: 'User',
    site_admin: false,
    name: 'Ezra Zygmuntowicz',
    company: 'Stuffstr PBC',
    blog: 'http://stuffstr.com',
    location: 'In the NW',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 22,
    public_gists: 106,
    followers: 524,
    following: 13,
    created_at: '2008-01-12T07:51:46Z',
    updated_at: '2022-02-22T15:05:20Z',
  },
  {
    login: 'evanphx',
    id: 7,
    node_id: 'MDQ6VXNlcjc=',
    avatar_url: 'https://avatars.githubusercontent.com/u/7?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/evanphx',
    html_url: 'https://github.com/evanphx',
    followers_url: 'https://api.github.com/users/evanphx/followers',
    following_url:
      'https://api.github.com/users/evanphx/following{/other_user}',
    gists_url: 'https://api.github.com/users/evanphx/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/evanphx/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/evanphx/subscriptions',
    organizations_url: 'https://api.github.com/users/evanphx/orgs',
    repos_url: 'https://api.github.com/users/evanphx/repos',
    events_url: 'https://api.github.com/users/evanphx/events{/privacy}',
    received_events_url: 'https://api.github.com/users/evanphx/received_events',
    type: 'User',
    site_admin: false,
    name: 'Evan Phoenix',
    company: '@hashicorp ',
    blog: 'http://blog.fallingsnow.net',
    location: 'Los Angeles, CA',
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 170,
    public_gists: 445,
    followers: 1446,
    following: 7,
    created_at: '2008-01-12T16:46:24Z',
    updated_at: '2021-12-13T22:27:09Z',
  },
];
